# -*- coding: utf-8 -*-
"""linear regression final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vzdt0NojDLT0xAar4kw2ScemqIvCauio
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

data= pd.read_csv("/content/drive/My Drive/datasheet.csv")

data.head()

X= data.iloc[:,:3].values

X.shape

X

y= data.iloc[:,-1].values

y.shape

import seaborn as sb
C_mat = data.corr()
fig = plt.figure(figsize = (15,15))

sb.heatmap(C_mat, annot= True, vmax = .8, square = True)
plt.show()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

y_train.shape

from sklearn.preprocessing import StandardScaler
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1,1))

y_train.shape

X_train.shape

from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

"""Linear Regression"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

y_pred = sc_y.inverse_transform(y_pred)

y_pred

y_test

from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test, y_pred))

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

